# Generated by Django 5.2.6 on 2025-11-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='match_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='match_image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='selected_gears',
            field=models.TextField(blank=True, null=True),
        ),
    ]
