# Generated by Django 5.2.6 on 2025-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0002_rating_match_distance_rating_match_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaminggear',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='proplayer',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gaminggear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gaming_gears/'),
        ),
        migrations.AddField(
            model_name='proplayer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proplayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pro_players/'),
        ),
        migrations.AddField(
            model_name='proplayer',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
