# Generated by Django 5.2.6 on 2025-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0003_remove_gaminggear_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
    ]
