# Generated by Django 5.2.6 on 2025-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaminggear',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
