# Generated by Django 5.2.6 on 2025-12-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0005_gaminggear_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
