# Generated by Django 5.2.10 on 2026-01-08 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0006_user_banned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.preset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'preset')},
            },
        ),
    ]
