# Generated by Django 5.2.6 on 2026-02-14 18:45

import django.db.models.deletion
from django.db import migrations, models



def clean_specs_data(apps, schema_editor):
    try:
        GamingGear = apps.get_model('APP01', 'GamingGear')
        # Update all to empty JSON object string '{}'
        GamingGear.objects.all().update(specs='{}')
    except Exception:
        pass

def clean_game_data(apps, schema_editor):
    try:
        ProPlayer = apps.get_model('APP01', 'ProPlayer')
        ProPlayer.objects.all().update(game=None)
    except Exception:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0009_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIModel',
        ),
        migrations.RemoveField(
            model_name='proplayer',
            name='physique_vector',
        ),
        migrations.AddField(
            model_name='proplayer',
            name='edpi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proplayer',
            name='sensitivity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        # FIX: Clean specs data using RunPython
        migrations.RunPython(clean_specs_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='gaminggear',
            name='specs',
            field=models.JSONField(blank=True, default=dict),
        ),
        # FIX: Make game nullable first
        migrations.AlterField(
            model_name='proplayer',
            name='game',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        # FIX: Clear game data using RunPython
        migrations.RunPython(clean_game_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proplayer',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_players', to='APP01.game'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
