# Generated by Django 5.1.6 on 2026-02-14 21:20

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0010_delete_aimodel_remove_proplayer_physique_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gaminggear',
            index=django.contrib.postgres.indexes.GinIndex(fields=['specs'], name='specs_gin_index'),
        ),
        migrations.AddConstraint(
            model_name='gaminggear',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
    ]
